### ISSUE TITLE
READMEに製品情報の追加

### ISSUE THREAD

**Issue by Hamumayo55** [jphacks/E_2202#30]
## やること
- [ ] 製品概要の背景・製品説明・特長・解決できること・今後の展望・注力したことを記入
- [ ] 開発技術の活用した技術項目を記入
- [ ] 独自技術を記入 (あれば)

## DONE定義
- [ ] メンバー全員のレビューを通す

**Comment by soto0201** [comment]
githubトップページのAboutも書いた方がいいかも
