### ISSUE TITLE
発表用のエレベータピッチを用意する

### ISSUE THREAD

**Issue by Hamumayo55** [jphacks/E_2202#65]

**Comment by Hamumayo55** [comment]
`エレベータピッチの例`
[ スクラムチームのスプリントを円滑にまわしたい ]   
[ enPiTを受講しているスクラムマスター]向けの,   
[ スクラムくん ]は  
[ スクラムマスターを支援するアプリ ]です.   
これは[ スプリントの流れをサポートする ]ことで  
[ 既存の時間管理アプリやスケジュールアプリ ]とは違って,  
[ スプリントイベントのメモや時間管理をしながらイベントの内容を確認することで、スプリントのリズムを作る事ができます.]

**Comment by Hamumayo55** [comment]
[ エラーを解決したい]
[ プログラミング初学者 ]向けの
[ YouQuery ]は
[ エラーから検索ワードを生成するアプリ ]です
これは[ 長いエラー文から重要な箇所がわからない初学者をサポート ]することで
[ 感覚頼りの検索や先輩やメンターなどに質問する ]ことは違って
[ 時間やコミュニケーションコストをかけずに的確な検索を1人で行うことができます ]

**Comment by kagari** [comment]
発表は終わったのでクローズにします！
